<?php
/**
 * @file
 * Hook implementations of the Mastodon Toot module.
 */

/**
 * Implements hook_node_insert().
 */
function mastotoot_node_insert(Node $node) {
  $content_type = config_get('mastotoot.settings', 'content_type');

  if ($node->type == $content_type && $node->status) {
    $toot = MastoToot::create($node);
    if ($toot) {
      $toot->submitToot();
    }
  }
}

/**
 * Implements hook_node_update().
 */
function mastotoot_node_update(Node $node) {
  $content_type = config_get('mastotoot.settings', 'content_type');

  if ($node->type == $content_type) {
    $new_status = $node->status;
    $original_status = $node->original->status;

    if ($new_status != $original_status) {
      $toot = MastoToot::create($node);
      if (!$toot) {
        return;
      }

      if ($new_status == NODE_PUBLISHED) {
        $toot->submitToot();
      }
      elseif ($new_status == NODE_NOT_PUBLISHED && $toot->isShared()) {
        $toot->deleteToot();
      }
    }
  }
}

/**
 * Implements hook_node_delete().
 */
function mastotoot_node_delete(Node $node) {
  $content_type = config_get('mastotoot.settings', 'content_type');

  if ($node->type == $content_type) {
    // @todo Maybe ignore type here (setting might have changed)?
    $toot = MastoToot::create($node);
    if ($toot && $toot->isShared()) {
      $toot->deleteToot();
    }
  }
}

/**
 * Implements hook_menu().
 */
function mastotoot_menu() {
  $items['admin/config/services/mastotoot'] = [
    'title' => 'Mastodon Toot',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('mastotoot_form'),
    'access arguments' => array('configure mastotoot'),
    'file' => 'mastotoot.admin.inc',
  ];
  $items['admin/config/services/mastotoot/settings'] = [
    'title' => 'Mastodon Toot settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  ];
  $items['admin/config/services/mastotoot/verify'] = [
    'title' => 'Verify credentials',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('mastotoot_verify_token_form'),
    'access arguments' => array('configure mastotoot'),
    'file' => 'mastotoot.admin.inc',
    'type' => MENU_LOCAL_TASK,
  ];
  return $items;
}

/**
 * Implements hook_permission().
 */
function mastotoot_permission() {
  return [
    'configure mastotoot' => [
      'title' => t('Configure Mastodon Toot'),
      'description' => t('Configure settings for the Mastodon Toot module.'),
    ],
  ];
}

/**
 * Implements hook_autoload_info().
 */
function mastotoot_autoload_info() {
  return [
    'MastoToot' => 'mastotoot.class.inc',
  ];
}

/**
 * Implements hook_config_info().
 */
function mastotoot_config_info() {
  $prefixes['mastotoot.settings'] = [
    'label' => t('Mastodon Toot settings'),
    'group' => t('Configuration'),
  ];
  return $prefixes;
}

/**
 * Implements hook_views_api().
 */
function mastotoot_views_api() {
  return [
    'api' => 3,
    'path' => backdrop_get_path('module', 'mastotoot'),
  ];
}
